"""add recipe and user tables

Revision ID: da9301b43279
Revises: 
Create Date: 2021-08-08 13:38:59.871519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9301b43279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_completionist', sa.Boolean(), nullable=False, default=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('planet', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('personality', sa.String(length=4096), nullable=False),
    sa.Column('main_ability', sa.String(length=256), nullable=False),
    sa.Column('quote', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_id'), 'character', ['id'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)

    op.create_table( 'association_table',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['user.id'], )
    )
    op.create_index(op.f('ix_assoc_character_id'), 'association_table', ['character_id'], unique=False)
    op.create_index(op.f('ix_assoc_user_id'), 'association_table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assoc_character_id'), table_name='character')
    op.drop_index(op.f('ix_assoc_user_id'), table_name='user')
    op.drop_table('association_table')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_character_id'), table_name='character')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
